---
title: "HW 01 - Airbnb listings in Edinburgh"
author: "Owen Bonneau"
date: "1/24/2023"
output: github_document
---

## Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse)
library(dsbox)
```

## Exercises
` 
### Exercise 1

13245 rows 

### Exercise 2

each row is a different airbnb listing, or property. 

### Exercise 3
I wanted it to the rows to have the same number of graphs so nrow had to be 1,2,7,or 14, and 2 lookjed the lease weird. 


```{r prices-neighbourhoods}
ggplot(data = edibnb, mapping = aes(x = price)) +
  geom_histogram(binwidth = 4) +
  facet_wrap(~neighbourhood, nrow=2)
```

### Exercise 4

Remove this text, and add your answer for Exercise 4 here.

```{r top-5-median}
# remove this comment and add the code for Exercise 4 here
```

```{r top-5-median-plot}
# remove this comment and add the code for Exercise 4 here
```

```{r top-5-median-summary-stats}
# remove this comment and add the code for Exercise 4 here
```

### Exercise 5

Remove this text, and add your answer for Exercise 5 here.

```{r review-scores-rating}
# remove this comment and add the code for Exercise 5 here
```